name: CheeseHuntStandalone
version: '2.0'
main: dev.byrt.cheesehunt.standalone.StandalonePlugin
api-version: '1.20'
authors: [ Byrt, 'lucyy.p' ]
description: Cheese Hunt standalone server components

dependencies:
  server:
    cheeselib:
      load: BEFORE
      join-classpath: true
